// ─── LEGAL ─── Terms of Service, Privacy Policy, Delete Account

// ── ToS / Privacy modal ───────────────────────────────────────────────────────
function showToS(tab) {
  tab = tab || 'tos';
  const overlay = document.getElementById('tos-overlay');
  if (overlay) overlay.style.display = 'flex';
  _tosRenderTab(tab);
}

function _tosRenderTab(tab) {
  const bodyEl   = document.getElementById('tos-body');
  const titleEl  = document.getElementById('tos-title');
  const tabTos   = document.getElementById('tos-tab-tos');
  const tabPriv  = document.getElementById('tos-tab-priv');

  const activeStyle   = 'flex:1;padding:9px;border:1px solid var(--bdr);background:var(--navy);color:#fff;font-family:var(--font);font-size:12px;font-weight:800;letter-spacing:.1em;text-transform:uppercase;cursor:pointer;';
  const inactiveStyle = 'flex:1;padding:9px;border:1px solid var(--bdr);background:transparent;color:var(--mut);font-family:var(--font);font-size:12px;font-weight:800;letter-spacing:.1em;text-transform:uppercase;cursor:pointer;';

  if (tab === 'tos') {
    if (tabTos)  { tabTos.style.cssText  = activeStyle   + 'border-radius:8px 0 0 8px;'; }
    if (tabPriv) { tabPriv.style.cssText = inactiveStyle + 'border-left:none;border-radius:0 8px 8px 0;'; }
    if (titleEl) titleEl.textContent = 'Terms of Service';
    if (bodyEl)  bodyEl.innerHTML = _tosContent();
  } else {
    if (tabTos)  { tabTos.style.cssText  = inactiveStyle + 'border-radius:8px 0 0 8px;'; }
    if (tabPriv) { tabPriv.style.cssText = activeStyle   + 'border-left:none;border-radius:0 8px 8px 0;'; }
    if (titleEl) titleEl.textContent = 'Privacy Policy';
    if (bodyEl)  bodyEl.innerHTML = _privacyContent();
  }
}

function _h(text) {
  return '<div style="font-family:var(--font);font-size:14px;font-weight:900;letter-spacing:.06em;text-transform:uppercase;color:var(--txt);margin:20px 0 6px;">' + text + '</div>';
}
function _p(text) {
  return '<p style="margin:0 0 12px;color:var(--mut);">' + text + '</p>';
}
function _ul(items) {
  return '<ul style="margin:0 0 12px;padding-left:18px;color:var(--mut);">'
    + items.map(function(i){ return '<li style="margin-bottom:6px;">' + i + '</li>'; }).join('')
    + '</ul>';
}

function _tosContent() {
  var eff = 'Last updated: June 2026';
  return '<div style="font-size:11px;color:var(--mut);margin-bottom:16px;">' + eff + '</div>'

  + _h('1. Acceptance of Terms')
  + _p('By accessing or using Racing Puzzle ("the App"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.')

  + _h('2. Eligibility')
  + _p('You must be at least <strong style="color:var(--txt);">18 years of age</strong> to use this App. By using the App you confirm that you are 18 or older. Racing Puzzle is intended for use in jurisdictions where online betting tracking is legal.')

  + _h('3. Nature of the Service')
  + _p('Racing Puzzle is a <strong style="color:var(--txt);">personal betting tracker and analysis tool</strong>. It does not facilitate, place, or process any bets or financial transactions. No real-money wagering takes place through this App.')
  + _p('Content generated by the App (including coach analysis, ratings, and edge calculations) is for <strong style="color:var(--txt);">informational purposes only</strong> and does not constitute financial or betting advice.')

  + _h('4. Your Account')
  + _ul([
    'You are responsible for maintaining the confidentiality of your login credentials.',
    'You are responsible for all activity that occurs under your account.',
    'You must provide accurate information when creating your account.',
    'You must notify us immediately of any unauthorised use of your account.'
  ])

  + _h('5. Acceptable Use')
  + _p('You agree not to:')
  + _ul([
    'Use the App for any unlawful purpose.',
    'Attempt to reverse-engineer, scrape, or disrupt the App or its infrastructure.',
    'Share your account credentials with others.',
    'Upload or transmit harmful, fraudulent, or misleading content.'
  ])

  + _h('6. Data and Privacy')
  + _p('Your use of the App is also governed by our Privacy Policy, which is incorporated into these Terms by reference.')

  + _h('7. Responsible Gambling')
  + _p('We take problem gambling seriously. If you feel your gambling is becoming a problem, please seek help immediately:')
  + _ul([
    '<a href="https://www.begambleaware.org" target="_blank" style="color:var(--gld2);">BeGambleAware.org</a>',
    '<a href="https://www.gamstop.co.uk" target="_blank" style="color:var(--gld2);">GamStop.co.uk</a> — free UK self-exclusion',
    'National Gambling Helpline: <strong style="color:var(--txt);">0808 8020 133</strong> (free, 24/7)'
  ])

  + _h('8. Intellectual Property')
  + _p('All content, design, and code within the App is owned by or licensed to Racing Puzzle. You may not copy, reproduce, or distribute any part of the App without prior written permission.')

  + _h('9. Disclaimers')
  + _p('The App is provided "as is" without warranties of any kind. We do not guarantee uninterrupted availability, accuracy of race data, or fitness for any particular purpose. Race data is sourced from third-party providers and may contain errors.')

  + _h('10. Limitation of Liability')
  + _p('To the fullest extent permitted by law, Racing Puzzle shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the App, including any betting losses.')

  + _h('11. Changes to These Terms')
  + _p('We may update these Terms from time to time. Continued use of the App after changes constitutes acceptance of the new Terms.')

  + _h('12. Contact')
  + _p('For any questions about these Terms, please contact us at <strong style="color:var(--txt);">support@theracingpuzzle.com</strong>.');
}

function _privacyContent() {
  var eff = 'Last updated: June 2026';
  return '<div style="font-size:11px;color:var(--mut);margin-bottom:16px;">' + eff + '</div>'

  + _h('1. Who We Are')
  + _p('Racing Puzzle ("we", "us", "our") operates the Racing Puzzle mobile web app. This Privacy Policy explains how we collect, use, and protect your personal data.')

  + _h('2. Data We Collect')
  + _p('We collect and store the following data when you use the App:')
  + _ul([
    '<strong style="color:var(--txt);">Account data</strong> — email address, hashed password (handled by Supabase Auth).',
    '<strong style="color:var(--txt);">Betting data</strong> — bet records, stakes, odds, results, and notes you enter.',
    '<strong style="color:var(--txt);">Horse profiles</strong> — profile notes, ratings, and race observations you create.',
    '<strong style="color:var(--txt);">Settings</strong> — staking plan, sources, and app preferences.',
    '<strong style="color:var(--txt);">Usage data</strong> — standard server logs (IP address, browser type) for security and debugging.'
  ])

  + _h('3. How We Use Your Data')
  + _ul([
    'To provide and operate the App and sync your data across devices.',
    'To send transactional emails (e.g. password reset).',
    'To improve the App based on aggregated, anonymised usage patterns.',
    'We do not sell your data to third parties.'
  ])

  + _h('4. Data Storage')
  + _p('Your data is stored securely on <a href="https://supabase.com" target="_blank" style="color:var(--gld2);">Supabase</a> infrastructure, hosted in the EU. All data in transit is encrypted via TLS. Row-Level Security ensures only you can access your own data.')

  + _h('5. Third-Party Services')
  + _ul([
    '<strong style="color:var(--txt);">Supabase</strong> — database, authentication, and storage.',
    '<strong style="color:var(--txt);">Cloudflare Workers</strong> — Racing API proxy (no personal data is sent to the proxy).',
    '<strong style="color:var(--txt);">theracingapi.com</strong> — live race data (anonymous requests only).'
  ])

  + _h('6. Your Rights (UK GDPR)')
  + _p('You have the right to:')
  + _ul([
    'Access the personal data we hold about you.',
    'Correct inaccurate data.',
    'Request deletion of your data ("right to be forgotten") — use the Delete Account button in Settings.',
    'Export your data — use the Export Data button in Settings.',
    'Object to or restrict certain processing.'
  ])

  + _h('7. Data Retention')
  + _p('Your data is retained for as long as your account is active. When you delete your account, all personal data is permanently removed from our systems within 30 days.')

  + _h('8. Cookies')
  + _p('The App uses browser <strong style="color:var(--txt);">localStorage</strong> to store your session and app state locally. No advertising or tracking cookies are used.')

  + _h('9. Children')
  + _p('The App is strictly for users aged 18 and over. We do not knowingly collect data from anyone under 18.')

  + _h('10. Contact')
  + _p('For privacy-related requests, contact us at <strong style="color:var(--txt);">privacy@theracingpuzzle.com</strong>.');
}

// ── Delete Account ────────────────────────────────────────────────────────────
function authDeleteAccountPrompt() {
  const overlay = document.getElementById('del-acct-overlay');
  const input   = document.getElementById('del-acct-confirm');
  const errEl   = document.getElementById('del-acct-error');
  const btn     = document.getElementById('del-acct-go');
  if (input)  input.value  = '';
  if (errEl)  errEl.textContent = '';
  if (btn)    { btn.disabled = true; btn.style.opacity = '.4'; }
  if (overlay) overlay.style.display = 'flex';
}

async function authDeleteAccount() {
  const btn   = document.getElementById('del-acct-go');
  const errEl = document.getElementById('del-acct-error');
  if (btn) { btn.disabled = true; btn.textContent = 'Deleting…'; btn.style.opacity = '.6'; }
  if (errEl) errEl.textContent = '';

  try {
    const token = _rpToken();
    const hdrs  = { 'apikey': SUPA_ANON, 'Authorization': 'Bearer ' + token, 'Content-Type': 'application/json' };

    // ── Step 1: Call the Edge Function — deletes data rows + auth user server-side ──
    // The Edge Function uses the service role key so it can call auth.admin.deleteUser.
    const fnUrl = SUPA_URL + '/functions/v1/delete-user';
    const fnRes = await fetch(fnUrl, { method: 'POST', headers: hdrs });

    if (!fnRes.ok) {
      // Edge Function not yet deployed — fall back to client-side data deletion only
      if (fnRes.status === 404 || fnRes.status === 401) {
        await _authDeleteDataOnly(token, hdrs);
      } else {
        const body = await fnRes.json().catch(function(){ return {}; });
        throw new Error(body.error || ('Server error ' + fnRes.status));
      }
    }

    // ── Step 2: Sign out and wipe local state ────────────────────────────────
    if (_rpAuthClient && _rpAuthClient.auth) {
      await _rpAuthClient.auth.signOut();
    }
    localStorage.clear();
    window.location.reload();

  } catch(e) {
    if (errEl) { errEl.style.color = '#ef4444'; errEl.textContent = 'Error: ' + e.message; }
    if (btn) { btn.disabled = false; btn.textContent = 'Delete My Account'; btn.style.opacity = ''; }
  }
}

// Fallback: delete all data rows client-side when Edge Function isn't deployed yet
async function _authDeleteDataOnly(token, hdrs) {
  const uid  = SUPA_USER_ID;
  const base = SUPA_URL + '/rest/v1/';
  const tables = [
    'profile_observations', 'profile_targets', 'horse_reviews',
    'horse_profiles', 'bets', 'daily_log', 'rules', 'settings', 'bank'
  ];
  for (var i = 0; i < tables.length; i++) {
    await fetch(base + tables[i] + '?user_id=eq.' + encodeURIComponent(uid), {
      method: 'DELETE', headers: hdrs
    });
  }
  // Can't delete auth user without service role — sign out is the best we can do
  if (_rpAuthClient && _rpAuthClient.auth) await _rpAuthClient.auth.signOut();
}

// Wire the disabled state to the button opacity
document.addEventListener('DOMContentLoaded', function() {
  var inp = document.getElementById('del-acct-confirm');
  var btn = document.getElementById('del-acct-go');
  if (inp && btn) {
    inp.addEventListener('input', function() {
      var match = inp.value === 'DELETE';
      btn.disabled = !match;
      btn.style.opacity = match ? '1' : '.4';
    });
  }
});
